[package]
name = "qdb-ast"
version = "0.1.0"
authors = ["VaskillerDev <Vaskoooo9241@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
log = "0.4"
lalrpop-util = "0.19.6"
regex = "1.5.4"

[build-dependencies]
lalrpop = "0.19.6"

[profile.release]
opt-level = 'z'
lto = true